FROM ghcr.io/actions/actions-runner:latest

USER root

RUN apt-get update && apt-get install -y \
    curl \
    jq \
    wget \
    git \
    gcc \
    python3 \
    python3-pip \
    python3-lxml\
    python3-xmltodict \
    libkrb5-dev \
    krb5-user \
    krb5-config \
    apt-transport-https \
    software-properties-common \
    sshpass \
     && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip3 install \
    ansible==10.6.0 \
    jmespath \
    pywinrm \
    pywinrm[kerberos] \ 
    future
 
# Install Ansible collections
RUN ansible-galaxy collection install \
    community.windows \
    azure.azcollection
 
# Copy and install Python requirements
COPY github/requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

# Install Powershell
RUN wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb \
&& dpkg -i packages-microsoft-prod.deb \
&& apt-get update \
&& apt-get install -y powershell

# Install Azure PowerShell Module
RUN pwsh -Command "Install-Module -Name Az -Force -AllowClobber -Scope AllUsers"

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install Terraform
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
&& echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list \
&& apt update && apt install terraform -y

COPY github/github.sh ./github.sh
RUN chmod +x ./github.sh

USER runner

ENTRYPOINT ["./github.sh"]
